version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testDB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5442:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
